"""Python version of Parmesan-bc2026/scripts/generate_bellman_ford.py
(via cpp/generators/generate_bellman_ford.py).

Emits bc2026/src/bestsofar/Utils/BellmanFordNavigator.py instead of
BellmanFordNavigator.java. The generated logic is line-for-line identical to
the Java generator's output (still checked in at
Parmesan-bc2026/src/bestsofar/Utils/BellmanFordNavigator.java); only the
syntax is translated per py/CONVENTIONS.md:

  Direction.WEST            -> Direction.WEST      (api Direction singletons)
  Vision.isDirt(loc) / bestsofar.Utils.Vision.isDirt(loc)
                            -> Vision.isDirt(loc)
  rc.xxx (inherited Globals.rc static)  -> Globals.rc.xxx
  1_000_000                 -> 1000000
  Direction d = null        -> d = None
  return null               -> return None
  c ? a : b                 -> a if c else b
  //if (canVisitN) { ... //} (dead commented wrapper) -> kept as # comments,
                              inner ifs run unconditionally as in the Java
"""

from pathlib import Path
from queue import Queue

checkRadius = 13

def distance(dx: int, dy: int) -> int:
    return dx ** 2 + dy ** 2

def direction(dx: int, dy: int) -> str:
    horizontal = {
        -1: "WEST",
        0: "",
        1: "EAST"
    }[dx]

    vertical = {
        -1: "SOUTH",
        0: "",
        1: "NORTH"
    }[dy]

    return f"Direction.{vertical}{horizontal}"

def main() -> None:
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (-1, 1), (1, -1), (1, 1)]
    offsets = {}

    queue = Queue()
    for dx, dy in directions:
        queue.put((dx, dy, 0, direction(dx, dy)))

    while not queue.empty():
        (dx, dy, previous_id, direction_from_previous) = queue.get()

        if (dx, dy) in offsets:
            continue

        id = len(offsets) + 1
        neighbors_before = []
        outer_ring = False

        for direction_dx, direction_dy in directions:
            new_dx, new_dy = dx + direction_dx, dy + direction_dy
            new_distance = distance(new_dx, new_dy)

            if new_distance < distance(dx, dy):
                if new_dx != 0 or new_dy != 0:
                    neighbors_before.append(offsets[(new_dx, new_dy)]["id"])
            elif new_distance <= checkRadius:
                queue.put((new_dx, new_dy, id, direction(direction_dx, direction_dy)))
            else:
                outer_ring = True

        offsets[(dx, dy)] = {
            "id": id,
            "previous_id": previous_id,
            "direction_from_previous": direction_from_previous,
            "outer_ring": outer_ring,
            "neighbors_before": neighbors_before,
            "neighbors_after": [],
        }

    for dx, dy in offsets:
        neighbors_after = offsets[(dx, dy)]["neighbors_after"]

        for direction_dx, direction_dy in directions:
            new_dx, new_dy = dx + direction_dx, dy + direction_dy
            new_distance = distance(new_dx, new_dy)

            if new_distance >= distance(dx, dy) and new_distance <= checkRadius:
                neighbors_after.append(offsets[(new_dx, new_dy)]["id"])

    offsets_by_distance = list(sorted(offsets.keys(), key=lambda item: distance(item[0], item[1])))

    content = """
# Generated by generators/generate_bellman_ford.py
from api import *
from Utils.Globals import Globals
from Utils.Vision import Vision


class BellmanFordNavigator(Globals):
    @staticmethod
    def getBestDirection(target):
    """.strip() + "\n"

    for dx, dy in offsets_by_distance:
        data = offsets[(dx, dy)]
        id = data["id"]

        if distance(dx, dy) > 2:
            continue

        content += f"""
        location{id} = Globals.rc.adjacentLocation({data['direction_from_previous']})
        canVisit{id} = (Globals.rc.canMove({direction(dx, dy)}) or Globals.rc.canRemoveDirt(location{id})) and not Vision.isDangerous(location{id})
        """.rstrip() + "\n"

    inner_ring_ids = [offsets[(dx, dy)]["id"] for dx, dy in offsets_by_distance if distance(dx, dy) <= 2]
    for id1 in inner_ring_ids:
        dx, dy = next((dx, dy) for dx, dy in offsets_by_distance if offsets[(dx, dy)]["id"] == id1)
        other_ids = [id2 for id2 in inner_ring_ids if id1 != id2]

        content += f"""
        if canVisit{id1} and {' and '.join(f'not canVisit{id2}' for id2 in other_ids)}:
            return {direction(dx, dy)}
        """.rstrip() + "\n"

    content += f"""
        if {' and '.join(f'not canVisit{id}' for id in inner_ring_ids)}:
            return None

    """.rstrip() + "\n"

### finish basic cases such as only 1 direction possible or none possible

    for dx, dy in offsets_by_distance:
        data = offsets[(dx, dy)]
        id = data["id"]

        content += f"""
        distance{id} = 1000000
        direction{id} = None
        """.rstrip() + "\n"

        if distance(dx, dy) > 2:
            content += f"""
        location{id} = location{data['previous_id']}.add({data['direction_from_previous']})
        canVisit{id} = Vision.hasSeenLocation(location{id}) and (Vision.isPassableWithDig(location{id}))
        weight{id} = ({2 + max(abs(dx), abs(dy))} if Vision.isDirt(location{id}) else 1) if canVisit{id} else 1000000
            """.rstrip()
        else:
            # Java emits `int weightN = ...` at column 0; Python needs method indent.
            # No trailing newline: the next block's leading \n terminates the line.
            content += f"        weight{id} = ({2 + max(abs(dx), abs(dy))} if Vision.isDirt(location{id}) else 1) if canVisit{id} else 1000000"



    for i, (side, ordered_offsets) in enumerate([
        ("before", offsets_by_distance),
        ("after", reversed(offsets_by_distance)),
        ("before", offsets_by_distance)
    ]):
        for dx, dy in ordered_offsets:
            data = offsets[(dx, dy)]
            id = data["id"]
            neighbors = data[f"neighbors_{side}"]

            if i == 0 and distance(dx, dy) <= 2:
                content += f"""
        if canVisit{id}:
            distance{id} = weight{id}
            direction{id} = {direction(dx, dy)}
                """.rstrip() + "\n"
                continue

            if len(neighbors) == 0:
                continue

            content += f"""
        #if (canVisit{id}) {{
            """.rstrip()

            for neighbor in neighbors:
                content += f"""
        if distance{neighbor} + weight{id} < distance{id}:
            distance{id} = distance{neighbor} + weight{id}
            direction{id} = direction{neighbor}
                """.rstrip()

                if neighbor != neighbors[-1]:
                    content += "\n"

            content += """
        #}
            """.rstrip() + "\n"

    content += """
        bestDirection = None  # Java: /*, secondDirection = null*/ stayed commented
        bestScore = 0  # Java: /*secondScore = 0,*/ score declared but uninitialised
        currentDistance = Globals.rc.getLocation().distanceSquaredTo(target)
    """.rstrip() + "\n"

    outer_ring_ids = [data["id"] for data in offsets.values() if data["outer_ring"]]
    for id in outer_ring_ids:
        content += f"""
        score = (currentDistance - location{id}.distanceSquaredTo(target)) / distance{id}
        # /*
        # if (score > secondScore) {{
        #     if (score > bestScore) {{
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction{id};
        #         bestScore = score;
        #     }} else {{
        #         secondDirection = direction{id};
        #         secondScore = score;
        #     }}
        # }}
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction{id}
        """.rstrip() + "\n"

    content += """
        #return secondDirection == null ? bestDirection : (rng.nextDouble() < secondBestMoveChance ? secondDirection : bestDirection);
        return bestDirection
    """.rstrip()

    output_dir = Path(__file__).resolve().parent.parent / "bc2026" / "src" / "bestsofar" / "Utils"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "BellmanFordNavigator.py"
    with output_file.open("w+", encoding="utf-8") as file:
        file.write(content.strip() + "\n")

if __name__ == "__main__":
    main()
