"""C++ version of Parmesan-bc2026/scripts/generate_bellman_ford.py.

Emits bc2026/generated/BellmanFordNavigator.hpp + .cpp instead of
BellmanFordNavigator.java. The generated logic is line-for-line identical to the
Java generator's output; only the syntax is translated per CONVENTIONS.md:

  Direction.WEST            -> Direction::all[Direction::WEST]
  Vision.isDirt(loc)        -> Vision::isDirt(loc)
  1_000_000                 -> 1000000
  Direction d = null        -> Direction d = NULL_DIRECTION  (CENTER sentinel)
  return null               -> return NULL_DIRECTION
"""

from pathlib import Path
from queue import Queue

checkRadius = 13

def distance(dx: int, dy: int) -> int:
    return dx ** 2 + dy ** 2

def direction(dx: int, dy: int) -> str:
    horizontal = {
        -1: "WEST",
        0: "",
        1: "EAST"
    }[dx]

    vertical = {
        -1: "SOUTH",
        0: "",
        1: "NORTH"
    }[dy]

    return f"Direction::all[Direction::{vertical}{horizontal}]"

HEADER = """
#pragma once
#include "../api.hpp"
#include "../src/bestsofar/Utils/Globals.hpp"

namespace Utils {

// Generated by generators/generate_bellman_ford.py
struct BellmanFordNavigator : Globals {
    // Java `null` Direction sentinel. CENTER is never one of the eight
    // candidate move directions, so it stands in for Java's null return.
    static constexpr Direction NULL_DIRECTION = Direction(Direction::CENTER, 0, 0);

    static Direction getBestDirection(MapLocation target);
};

}  // namespace Utils
""".strip() + "\n"

def main() -> None:
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (-1, 1), (1, -1), (1, 1)]
    offsets = {}

    queue = Queue()
    for dx, dy in directions:
        queue.put((dx, dy, 0, direction(dx, dy)))

    while not queue.empty():
        (dx, dy, previous_id, direction_from_previous) = queue.get()

        if (dx, dy) in offsets:
            continue

        id = len(offsets) + 1
        neighbors_before = []
        outer_ring = False

        for direction_dx, direction_dy in directions:
            new_dx, new_dy = dx + direction_dx, dy + direction_dy
            new_distance = distance(new_dx, new_dy)

            if new_distance < distance(dx, dy):
                if new_dx != 0 or new_dy != 0:
                    neighbors_before.append(offsets[(new_dx, new_dy)]["id"])
            elif new_distance <= checkRadius:
                queue.put((new_dx, new_dy, id, direction(direction_dx, direction_dy)))
            else:
                outer_ring = True

        offsets[(dx, dy)] = {
            "id": id,
            "previous_id": previous_id,
            "direction_from_previous": direction_from_previous,
            "outer_ring": outer_ring,
            "neighbors_before": neighbors_before,
            "neighbors_after": [],
        }

    for dx, dy in offsets:
        neighbors_after = offsets[(dx, dy)]["neighbors_after"]

        for direction_dx, direction_dy in directions:
            new_dx, new_dy = dx + direction_dx, dy + direction_dy
            new_distance = distance(new_dx, new_dy)

            if new_distance >= distance(dx, dy) and new_distance <= checkRadius:
                neighbors_after.append(offsets[(new_dx, new_dy)]["id"])

    offsets_by_distance = list(sorted(offsets.keys(), key=lambda item: distance(item[0], item[1])))

    content = f"""
#include "BellmanFordNavigator.hpp"
#include "../api.hpp"
#include "../src/bestsofar/Utils/Globals.hpp"
#include "../src/bestsofar/Utils/Vision.hpp"

// Generated by generators/generate_bellman_ford.py
namespace Utils {{

Direction BellmanFordNavigator::getBestDirection(MapLocation target) {{
    """.strip() + "\n"

    for dx, dy in offsets_by_distance:
        data = offsets[(dx, dy)]
        id = data["id"]

        if distance(dx, dy) > 2:
            continue

        content += f"""
        MapLocation location{id} = rc.adjacentLocation({data['direction_from_previous']});
        bool canVisit{id} = (rc.canMove({direction(dx, dy)}) || rc.canRemoveDirt(location{id})) && !Vision::isDangerous(location{id});
        """.rstrip() + "\n"

    inner_ring_ids = [offsets[(dx, dy)]["id"] for dx, dy in offsets_by_distance if distance(dx, dy) <= 2]
    for id1 in inner_ring_ids:
        dx, dy = next((dx, dy) for dx, dy in offsets_by_distance if offsets[(dx, dy)]["id"] == id1)
        other_ids = [id2 for id2 in inner_ring_ids if id1 != id2]

        content += f"""
        if (canVisit{id1} && {' && '.join(f'!canVisit{id2}' for id2 in other_ids)}) {{
            return {direction(dx, dy)};
        }}
        """.rstrip() + "\n"

    content += f"""
        if ({' && '.join(f'!canVisit{id}' for id in inner_ring_ids)}) {{
            return NULL_DIRECTION;
        }}

    """.rstrip() + "\n"

### finish basic cases such as only 1 direction possible or none possible

    for dx, dy in offsets_by_distance:
        data = offsets[(dx, dy)]
        id = data["id"]

        content += f"""
        int distance{id} = 1000000;
        Direction direction{id} = NULL_DIRECTION;
        """.rstrip() + "\n"

        if distance(dx, dy) > 2:
            content += f"""
        MapLocation location{id} = location{data['previous_id']}.add({data['direction_from_previous']});
        bool canVisit{id} = Vision::hasSeenLocation(location{id}) && (Vision::isPassableWithDig(location{id}));
        int weight{id} = canVisit{id} ? (Vision::isDirt(location{id}) ? {2 + max(abs(dx), abs(dy))} : 1) : 1000000;
            """.rstrip()
        else:
            content += f"""
        int weight{id} = canVisit{id} ? (Vision::isDirt(location{id}) ? {2 + max(abs(dx), abs(dy))} : 1) : 1000000;
            """.strip()



    for i, (side, ordered_offsets) in enumerate([
        ("before", offsets_by_distance),
        ("after", reversed(offsets_by_distance)),
        ("before", offsets_by_distance)
    ]):
        for dx, dy in ordered_offsets:
            data = offsets[(dx, dy)]
            id = data["id"]
            neighbors = data[f"neighbors_{side}"]

            if i == 0 and distance(dx, dy) <= 2:
                content += f"""
        if (canVisit{id}) {{
            distance{id} = weight{id};
            direction{id} = {direction(dx, dy)};
        }}
                """.rstrip() + "\n"
                continue

            if len(neighbors) == 0:
                continue

            content += f"""
        //if (canVisit{id}) {{
            """.rstrip()

            for neighbor in neighbors:
                content += f"""
            if (distance{neighbor} + weight{id} < distance{id}) {{
                distance{id} = distance{neighbor} + weight{id};
                direction{id} = direction{neighbor};
            }}
                """.rstrip()

                if neighbor != neighbors[-1]:
                    content += "\n"

            content += """
        //}
            """.rstrip() + "\n"

    content += f"""
        Direction bestDirection = NULL_DIRECTION/*, secondDirection = NULL_DIRECTION*/;
        double bestScore = 0, /*secondScore = 0,*/ score;
        int currentDistance = rc.getLocation().distanceSquaredTo(target);
    """.rstrip() + "\n"

    outer_ring_ids = [data["id"] for data in offsets.values() if data["outer_ring"]]
    for id in outer_ring_ids:
        content += f"""
        score = (double) (currentDistance - location{id}.distanceSquaredTo(target)) / (double) distance{id};
        /*
        if (score > secondScore) {{
            if (score > bestScore) {{
                secondDirection = bestDirection;
                secondScore = bestScore;
                bestDirection = direction{id};
                bestScore = score;
            }} else {{
                secondDirection = direction{id};
                secondScore = score;
            }}
        }}
        */
        if (score > bestScore) {{
            bestScore = score;
            bestDirection = direction{id};
        }}
        """.rstrip() + "\n"

    content += """
        //return secondDirection == NULL_DIRECTION ? bestDirection : (rng.nextDouble() < secondBestMoveChance ? secondDirection : bestDirection);
        return bestDirection;
}

}  // namespace Utils
    """.rstrip()

    output_dir = Path(__file__).resolve().parent.parent / "bc2026" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    header_file = output_dir / "BellmanFordNavigator.hpp"
    with header_file.open("w+", encoding="utf-8") as file:
        file.write(HEADER)

    output_file = output_dir / "BellmanFordNavigator.cpp"
    with output_file.open("w+", encoding="utf-8") as file:
        file.write(content.strip() + "\n")

if __name__ == "__main__":
    main()
