#pragma once
#include "api.hpp"
#include "Utils/Globals.hpp"

namespace Utils {

// Generated by scripts/generate_bellman_ford.py
struct BellmanFordNavigatorCat : Globals {
    // Java returns null when no direction qualifies - impl must pick a
    // Direction null-sentinel convention (see notes).
    static Direction getBestDirection(MapLocation target);
};

}  // namespace Utils
