# Generated by generators/generate_bellman_ford.py
from api import *
from Utils.Globals import Globals
from Utils.Vision import Vision


class BellmanFordNavigator(Globals):
    @staticmethod
    def getBestDirection(target):

        location1 = Globals.rc.adjacentLocation(Direction.WEST)
        canVisit1 = (Globals.rc.canMove(Direction.WEST) or Globals.rc.canRemoveDirt(location1)) and not Vision.isDangerous(location1)

        location2 = Globals.rc.adjacentLocation(Direction.EAST)
        canVisit2 = (Globals.rc.canMove(Direction.EAST) or Globals.rc.canRemoveDirt(location2)) and not Vision.isDangerous(location2)

        location3 = Globals.rc.adjacentLocation(Direction.SOUTH)
        canVisit3 = (Globals.rc.canMove(Direction.SOUTH) or Globals.rc.canRemoveDirt(location3)) and not Vision.isDangerous(location3)

        location4 = Globals.rc.adjacentLocation(Direction.NORTH)
        canVisit4 = (Globals.rc.canMove(Direction.NORTH) or Globals.rc.canRemoveDirt(location4)) and not Vision.isDangerous(location4)

        location5 = Globals.rc.adjacentLocation(Direction.SOUTHWEST)
        canVisit5 = (Globals.rc.canMove(Direction.SOUTHWEST) or Globals.rc.canRemoveDirt(location5)) and not Vision.isDangerous(location5)

        location6 = Globals.rc.adjacentLocation(Direction.NORTHWEST)
        canVisit6 = (Globals.rc.canMove(Direction.NORTHWEST) or Globals.rc.canRemoveDirt(location6)) and not Vision.isDangerous(location6)

        location7 = Globals.rc.adjacentLocation(Direction.SOUTHEAST)
        canVisit7 = (Globals.rc.canMove(Direction.SOUTHEAST) or Globals.rc.canRemoveDirt(location7)) and not Vision.isDangerous(location7)

        location8 = Globals.rc.adjacentLocation(Direction.NORTHEAST)
        canVisit8 = (Globals.rc.canMove(Direction.NORTHEAST) or Globals.rc.canRemoveDirt(location8)) and not Vision.isDangerous(location8)

        if canVisit1 and not canVisit2 and not canVisit3 and not canVisit4 and not canVisit5 and not canVisit6 and not canVisit7 and not canVisit8:
            return Direction.WEST

        if canVisit2 and not canVisit1 and not canVisit3 and not canVisit4 and not canVisit5 and not canVisit6 and not canVisit7 and not canVisit8:
            return Direction.EAST

        if canVisit3 and not canVisit1 and not canVisit2 and not canVisit4 and not canVisit5 and not canVisit6 and not canVisit7 and not canVisit8:
            return Direction.SOUTH

        if canVisit4 and not canVisit1 and not canVisit2 and not canVisit3 and not canVisit5 and not canVisit6 and not canVisit7 and not canVisit8:
            return Direction.NORTH

        if canVisit5 and not canVisit1 and not canVisit2 and not canVisit3 and not canVisit4 and not canVisit6 and not canVisit7 and not canVisit8:
            return Direction.SOUTHWEST

        if canVisit6 and not canVisit1 and not canVisit2 and not canVisit3 and not canVisit4 and not canVisit5 and not canVisit7 and not canVisit8:
            return Direction.NORTHWEST

        if canVisit7 and not canVisit1 and not canVisit2 and not canVisit3 and not canVisit4 and not canVisit5 and not canVisit6 and not canVisit8:
            return Direction.SOUTHEAST

        if canVisit8 and not canVisit1 and not canVisit2 and not canVisit3 and not canVisit4 and not canVisit5 and not canVisit6 and not canVisit7:
            return Direction.NORTHEAST

        if not canVisit1 and not canVisit2 and not canVisit3 and not canVisit4 and not canVisit5 and not canVisit6 and not canVisit7 and not canVisit8:
            return None

        distance1 = 1000000
        direction1 = None
        weight1 = (3 if Vision.isDirt(location1) else 1) if canVisit1 else 1000000
        distance2 = 1000000
        direction2 = None
        weight2 = (3 if Vision.isDirt(location2) else 1) if canVisit2 else 1000000
        distance3 = 1000000
        direction3 = None
        weight3 = (3 if Vision.isDirt(location3) else 1) if canVisit3 else 1000000
        distance4 = 1000000
        direction4 = None
        weight4 = (3 if Vision.isDirt(location4) else 1) if canVisit4 else 1000000
        distance5 = 1000000
        direction5 = None
        weight5 = (3 if Vision.isDirt(location5) else 1) if canVisit5 else 1000000
        distance6 = 1000000
        direction6 = None
        weight6 = (3 if Vision.isDirt(location6) else 1) if canVisit6 else 1000000
        distance7 = 1000000
        direction7 = None
        weight7 = (3 if Vision.isDirt(location7) else 1) if canVisit7 else 1000000
        distance8 = 1000000
        direction8 = None
        weight8 = (3 if Vision.isDirt(location8) else 1) if canVisit8 else 1000000
        distance9 = 1000000
        direction9 = None

        location9 = location1.add(Direction.WEST)
        canVisit9 = Vision.hasSeenLocation(location9) and (Vision.isPassableWithDig(location9))
        weight9 = (4 if Vision.isDirt(location9) else 1) if canVisit9 else 1000000
        distance12 = 1000000
        direction12 = None

        location12 = location2.add(Direction.EAST)
        canVisit12 = Vision.hasSeenLocation(location12) and (Vision.isPassableWithDig(location12))
        weight12 = (4 if Vision.isDirt(location12) else 1) if canVisit12 else 1000000
        distance15 = 1000000
        direction15 = None

        location15 = location3.add(Direction.SOUTH)
        canVisit15 = Vision.hasSeenLocation(location15) and (Vision.isPassableWithDig(location15))
        weight15 = (4 if Vision.isDirt(location15) else 1) if canVisit15 else 1000000
        distance18 = 1000000
        direction18 = None

        location18 = location4.add(Direction.NORTH)
        canVisit18 = Vision.hasSeenLocation(location18) and (Vision.isPassableWithDig(location18))
        weight18 = (4 if Vision.isDirt(location18) else 1) if canVisit18 else 1000000
        distance10 = 1000000
        direction10 = None

        location10 = location1.add(Direction.SOUTHWEST)
        canVisit10 = Vision.hasSeenLocation(location10) and (Vision.isPassableWithDig(location10))
        weight10 = (4 if Vision.isDirt(location10) else 1) if canVisit10 else 1000000
        distance11 = 1000000
        direction11 = None

        location11 = location1.add(Direction.NORTHWEST)
        canVisit11 = Vision.hasSeenLocation(location11) and (Vision.isPassableWithDig(location11))
        weight11 = (4 if Vision.isDirt(location11) else 1) if canVisit11 else 1000000
        distance13 = 1000000
        direction13 = None

        location13 = location2.add(Direction.SOUTHEAST)
        canVisit13 = Vision.hasSeenLocation(location13) and (Vision.isPassableWithDig(location13))
        weight13 = (4 if Vision.isDirt(location13) else 1) if canVisit13 else 1000000
        distance14 = 1000000
        direction14 = None

        location14 = location2.add(Direction.NORTHEAST)
        canVisit14 = Vision.hasSeenLocation(location14) and (Vision.isPassableWithDig(location14))
        weight14 = (4 if Vision.isDirt(location14) else 1) if canVisit14 else 1000000
        distance16 = 1000000
        direction16 = None

        location16 = location3.add(Direction.SOUTHWEST)
        canVisit16 = Vision.hasSeenLocation(location16) and (Vision.isPassableWithDig(location16))
        weight16 = (4 if Vision.isDirt(location16) else 1) if canVisit16 else 1000000
        distance17 = 1000000
        direction17 = None

        location17 = location3.add(Direction.SOUTHEAST)
        canVisit17 = Vision.hasSeenLocation(location17) and (Vision.isPassableWithDig(location17))
        weight17 = (4 if Vision.isDirt(location17) else 1) if canVisit17 else 1000000
        distance19 = 1000000
        direction19 = None

        location19 = location4.add(Direction.NORTHWEST)
        canVisit19 = Vision.hasSeenLocation(location19) and (Vision.isPassableWithDig(location19))
        weight19 = (4 if Vision.isDirt(location19) else 1) if canVisit19 else 1000000
        distance20 = 1000000
        direction20 = None

        location20 = location4.add(Direction.NORTHEAST)
        canVisit20 = Vision.hasSeenLocation(location20) and (Vision.isPassableWithDig(location20))
        weight20 = (4 if Vision.isDirt(location20) else 1) if canVisit20 else 1000000
        distance21 = 1000000
        direction21 = None

        location21 = location5.add(Direction.SOUTHWEST)
        canVisit21 = Vision.hasSeenLocation(location21) and (Vision.isPassableWithDig(location21))
        weight21 = (4 if Vision.isDirt(location21) else 1) if canVisit21 else 1000000
        distance22 = 1000000
        direction22 = None

        location22 = location6.add(Direction.NORTHWEST)
        canVisit22 = Vision.hasSeenLocation(location22) and (Vision.isPassableWithDig(location22))
        weight22 = (4 if Vision.isDirt(location22) else 1) if canVisit22 else 1000000
        distance23 = 1000000
        direction23 = None

        location23 = location7.add(Direction.SOUTHEAST)
        canVisit23 = Vision.hasSeenLocation(location23) and (Vision.isPassableWithDig(location23))
        weight23 = (4 if Vision.isDirt(location23) else 1) if canVisit23 else 1000000
        distance24 = 1000000
        direction24 = None

        location24 = location8.add(Direction.NORTHEAST)
        canVisit24 = Vision.hasSeenLocation(location24) and (Vision.isPassableWithDig(location24))
        weight24 = (4 if Vision.isDirt(location24) else 1) if canVisit24 else 1000000
        distance25 = 1000000
        direction25 = None

        location25 = location9.add(Direction.WEST)
        canVisit25 = Vision.hasSeenLocation(location25) and (Vision.isPassableWithDig(location25))
        weight25 = (5 if Vision.isDirt(location25) else 1) if canVisit25 else 1000000
        distance30 = 1000000
        direction30 = None

        location30 = location12.add(Direction.EAST)
        canVisit30 = Vision.hasSeenLocation(location30) and (Vision.isPassableWithDig(location30))
        weight30 = (5 if Vision.isDirt(location30) else 1) if canVisit30 else 1000000
        distance35 = 1000000
        direction35 = None

        location35 = location15.add(Direction.SOUTH)
        canVisit35 = Vision.hasSeenLocation(location35) and (Vision.isPassableWithDig(location35))
        weight35 = (5 if Vision.isDirt(location35) else 1) if canVisit35 else 1000000
        distance40 = 1000000
        direction40 = None

        location40 = location18.add(Direction.NORTH)
        canVisit40 = Vision.hasSeenLocation(location40) and (Vision.isPassableWithDig(location40))
        weight40 = (5 if Vision.isDirt(location40) else 1) if canVisit40 else 1000000
        distance26 = 1000000
        direction26 = None

        location26 = location9.add(Direction.SOUTHWEST)
        canVisit26 = Vision.hasSeenLocation(location26) and (Vision.isPassableWithDig(location26))
        weight26 = (5 if Vision.isDirt(location26) else 1) if canVisit26 else 1000000
        distance27 = 1000000
        direction27 = None

        location27 = location9.add(Direction.NORTHWEST)
        canVisit27 = Vision.hasSeenLocation(location27) and (Vision.isPassableWithDig(location27))
        weight27 = (5 if Vision.isDirt(location27) else 1) if canVisit27 else 1000000
        distance31 = 1000000
        direction31 = None

        location31 = location12.add(Direction.SOUTHEAST)
        canVisit31 = Vision.hasSeenLocation(location31) and (Vision.isPassableWithDig(location31))
        weight31 = (5 if Vision.isDirt(location31) else 1) if canVisit31 else 1000000
        distance32 = 1000000
        direction32 = None

        location32 = location12.add(Direction.NORTHEAST)
        canVisit32 = Vision.hasSeenLocation(location32) and (Vision.isPassableWithDig(location32))
        weight32 = (5 if Vision.isDirt(location32) else 1) if canVisit32 else 1000000
        distance36 = 1000000
        direction36 = None

        location36 = location15.add(Direction.SOUTHWEST)
        canVisit36 = Vision.hasSeenLocation(location36) and (Vision.isPassableWithDig(location36))
        weight36 = (5 if Vision.isDirt(location36) else 1) if canVisit36 else 1000000
        distance37 = 1000000
        direction37 = None

        location37 = location15.add(Direction.SOUTHEAST)
        canVisit37 = Vision.hasSeenLocation(location37) and (Vision.isPassableWithDig(location37))
        weight37 = (5 if Vision.isDirt(location37) else 1) if canVisit37 else 1000000
        distance41 = 1000000
        direction41 = None

        location41 = location18.add(Direction.NORTHWEST)
        canVisit41 = Vision.hasSeenLocation(location41) and (Vision.isPassableWithDig(location41))
        weight41 = (5 if Vision.isDirt(location41) else 1) if canVisit41 else 1000000
        distance42 = 1000000
        direction42 = None

        location42 = location18.add(Direction.NORTHEAST)
        canVisit42 = Vision.hasSeenLocation(location42) and (Vision.isPassableWithDig(location42))
        weight42 = (5 if Vision.isDirt(location42) else 1) if canVisit42 else 1000000
        distance28 = 1000000
        direction28 = None

        location28 = location10.add(Direction.SOUTHWEST)
        canVisit28 = Vision.hasSeenLocation(location28) and (Vision.isPassableWithDig(location28))
        weight28 = (5 if Vision.isDirt(location28) else 1) if canVisit28 else 1000000
        distance29 = 1000000
        direction29 = None

        location29 = location11.add(Direction.NORTHWEST)
        canVisit29 = Vision.hasSeenLocation(location29) and (Vision.isPassableWithDig(location29))
        weight29 = (5 if Vision.isDirt(location29) else 1) if canVisit29 else 1000000
        distance33 = 1000000
        direction33 = None

        location33 = location13.add(Direction.SOUTHEAST)
        canVisit33 = Vision.hasSeenLocation(location33) and (Vision.isPassableWithDig(location33))
        weight33 = (5 if Vision.isDirt(location33) else 1) if canVisit33 else 1000000
        distance34 = 1000000
        direction34 = None

        location34 = location14.add(Direction.NORTHEAST)
        canVisit34 = Vision.hasSeenLocation(location34) and (Vision.isPassableWithDig(location34))
        weight34 = (5 if Vision.isDirt(location34) else 1) if canVisit34 else 1000000
        distance38 = 1000000
        direction38 = None

        location38 = location16.add(Direction.SOUTHWEST)
        canVisit38 = Vision.hasSeenLocation(location38) and (Vision.isPassableWithDig(location38))
        weight38 = (5 if Vision.isDirt(location38) else 1) if canVisit38 else 1000000
        distance39 = 1000000
        direction39 = None

        location39 = location17.add(Direction.SOUTHEAST)
        canVisit39 = Vision.hasSeenLocation(location39) and (Vision.isPassableWithDig(location39))
        weight39 = (5 if Vision.isDirt(location39) else 1) if canVisit39 else 1000000
        distance43 = 1000000
        direction43 = None

        location43 = location19.add(Direction.NORTHWEST)
        canVisit43 = Vision.hasSeenLocation(location43) and (Vision.isPassableWithDig(location43))
        weight43 = (5 if Vision.isDirt(location43) else 1) if canVisit43 else 1000000
        distance44 = 1000000
        direction44 = None

        location44 = location20.add(Direction.NORTHEAST)
        canVisit44 = Vision.hasSeenLocation(location44) and (Vision.isPassableWithDig(location44))
        weight44 = (5 if Vision.isDirt(location44) else 1) if canVisit44 else 1000000
        if canVisit1:
            distance1 = weight1
            direction1 = Direction.WEST

        if canVisit2:
            distance2 = weight2
            direction2 = Direction.EAST

        if canVisit3:
            distance3 = weight3
            direction3 = Direction.SOUTH

        if canVisit4:
            distance4 = weight4
            direction4 = Direction.NORTH

        if canVisit5:
            distance5 = weight5
            direction5 = Direction.SOUTHWEST

        if canVisit6:
            distance6 = weight6
            direction6 = Direction.NORTHWEST

        if canVisit7:
            distance7 = weight7
            direction7 = Direction.SOUTHEAST

        if canVisit8:
            distance8 = weight8
            direction8 = Direction.NORTHEAST

        #if (canVisit9) {
        if distance1 + weight9 < distance9:
            distance9 = distance1 + weight9
            direction9 = direction1

        if distance5 + weight9 < distance9:
            distance9 = distance5 + weight9
            direction9 = direction5

        if distance6 + weight9 < distance9:
            distance9 = distance6 + weight9
            direction9 = direction6
        #}

        #if (canVisit12) {
        if distance2 + weight12 < distance12:
            distance12 = distance2 + weight12
            direction12 = direction2

        if distance7 + weight12 < distance12:
            distance12 = distance7 + weight12
            direction12 = direction7

        if distance8 + weight12 < distance12:
            distance12 = distance8 + weight12
            direction12 = direction8
        #}

        #if (canVisit15) {
        if distance3 + weight15 < distance15:
            distance15 = distance3 + weight15
            direction15 = direction3

        if distance5 + weight15 < distance15:
            distance15 = distance5 + weight15
            direction15 = direction5

        if distance7 + weight15 < distance15:
            distance15 = distance7 + weight15
            direction15 = direction7
        #}

        #if (canVisit18) {
        if distance4 + weight18 < distance18:
            distance18 = distance4 + weight18
            direction18 = direction4

        if distance6 + weight18 < distance18:
            distance18 = distance6 + weight18
            direction18 = direction6

        if distance8 + weight18 < distance18:
            distance18 = distance8 + weight18
            direction18 = direction8
        #}

        #if (canVisit10) {
        if distance5 + weight10 < distance10:
            distance10 = distance5 + weight10
            direction10 = direction5

        if distance9 + weight10 < distance10:
            distance10 = distance9 + weight10
            direction10 = direction9

        if distance1 + weight10 < distance10:
            distance10 = distance1 + weight10
            direction10 = direction1
        #}

        #if (canVisit11) {
        if distance6 + weight11 < distance11:
            distance11 = distance6 + weight11
            direction11 = direction6

        if distance9 + weight11 < distance11:
            distance11 = distance9 + weight11
            direction11 = direction9

        if distance1 + weight11 < distance11:
            distance11 = distance1 + weight11
            direction11 = direction1
        #}

        #if (canVisit13) {
        if distance7 + weight13 < distance13:
            distance13 = distance7 + weight13
            direction13 = direction7

        if distance12 + weight13 < distance13:
            distance13 = distance12 + weight13
            direction13 = direction12

        if distance2 + weight13 < distance13:
            distance13 = distance2 + weight13
            direction13 = direction2
        #}

        #if (canVisit14) {
        if distance8 + weight14 < distance14:
            distance14 = distance8 + weight14
            direction14 = direction8

        if distance12 + weight14 < distance14:
            distance14 = distance12 + weight14
            direction14 = direction12

        if distance2 + weight14 < distance14:
            distance14 = distance2 + weight14
            direction14 = direction2
        #}

        #if (canVisit16) {
        if distance15 + weight16 < distance16:
            distance16 = distance15 + weight16
            direction16 = direction15

        if distance5 + weight16 < distance16:
            distance16 = distance5 + weight16
            direction16 = direction5

        if distance3 + weight16 < distance16:
            distance16 = distance3 + weight16
            direction16 = direction3
        #}

        #if (canVisit17) {
        if distance15 + weight17 < distance17:
            distance17 = distance15 + weight17
            direction17 = direction15

        if distance7 + weight17 < distance17:
            distance17 = distance7 + weight17
            direction17 = direction7

        if distance3 + weight17 < distance17:
            distance17 = distance3 + weight17
            direction17 = direction3
        #}

        #if (canVisit19) {
        if distance18 + weight19 < distance19:
            distance19 = distance18 + weight19
            direction19 = direction18

        if distance6 + weight19 < distance19:
            distance19 = distance6 + weight19
            direction19 = direction6

        if distance4 + weight19 < distance19:
            distance19 = distance4 + weight19
            direction19 = direction4
        #}

        #if (canVisit20) {
        if distance18 + weight20 < distance20:
            distance20 = distance18 + weight20
            direction20 = direction18

        if distance8 + weight20 < distance20:
            distance20 = distance8 + weight20
            direction20 = direction8

        if distance4 + weight20 < distance20:
            distance20 = distance4 + weight20
            direction20 = direction4
        #}

        #if (canVisit21) {
        if distance16 + weight21 < distance21:
            distance21 = distance16 + weight21
            direction21 = direction16

        if distance10 + weight21 < distance21:
            distance21 = distance10 + weight21
            direction21 = direction10

        if distance5 + weight21 < distance21:
            distance21 = distance5 + weight21
            direction21 = direction5
        #}

        #if (canVisit22) {
        if distance19 + weight22 < distance22:
            distance22 = distance19 + weight22
            direction22 = direction19

        if distance11 + weight22 < distance22:
            distance22 = distance11 + weight22
            direction22 = direction11

        if distance6 + weight22 < distance22:
            distance22 = distance6 + weight22
            direction22 = direction6
        #}

        #if (canVisit23) {
        if distance17 + weight23 < distance23:
            distance23 = distance17 + weight23
            direction23 = direction17

        if distance13 + weight23 < distance23:
            distance23 = distance13 + weight23
            direction23 = direction13

        if distance7 + weight23 < distance23:
            distance23 = distance7 + weight23
            direction23 = direction7
        #}

        #if (canVisit24) {
        if distance20 + weight24 < distance24:
            distance24 = distance20 + weight24
            direction24 = direction20

        if distance14 + weight24 < distance24:
            distance24 = distance14 + weight24
            direction24 = direction14

        if distance8 + weight24 < distance24:
            distance24 = distance8 + weight24
            direction24 = direction8
        #}

        #if (canVisit25) {
        if distance9 + weight25 < distance25:
            distance25 = distance9 + weight25
            direction25 = direction9

        if distance10 + weight25 < distance25:
            distance25 = distance10 + weight25
            direction25 = direction10

        if distance11 + weight25 < distance25:
            distance25 = distance11 + weight25
            direction25 = direction11
        #}

        #if (canVisit30) {
        if distance12 + weight30 < distance30:
            distance30 = distance12 + weight30
            direction30 = direction12

        if distance13 + weight30 < distance30:
            distance30 = distance13 + weight30
            direction30 = direction13

        if distance14 + weight30 < distance30:
            distance30 = distance14 + weight30
            direction30 = direction14
        #}

        #if (canVisit35) {
        if distance15 + weight35 < distance35:
            distance35 = distance15 + weight35
            direction35 = direction15

        if distance16 + weight35 < distance35:
            distance35 = distance16 + weight35
            direction35 = direction16

        if distance17 + weight35 < distance35:
            distance35 = distance17 + weight35
            direction35 = direction17
        #}

        #if (canVisit40) {
        if distance18 + weight40 < distance40:
            distance40 = distance18 + weight40
            direction40 = direction18

        if distance19 + weight40 < distance40:
            distance40 = distance19 + weight40
            direction40 = direction19

        if distance20 + weight40 < distance40:
            distance40 = distance20 + weight40
            direction40 = direction20
        #}

        #if (canVisit26) {
        if distance10 + weight26 < distance26:
            distance26 = distance10 + weight26
            direction26 = direction10

        if distance25 + weight26 < distance26:
            distance26 = distance25 + weight26
            direction26 = direction25

        if distance21 + weight26 < distance26:
            distance26 = distance21 + weight26
            direction26 = direction21

        if distance9 + weight26 < distance26:
            distance26 = distance9 + weight26
            direction26 = direction9
        #}

        #if (canVisit27) {
        if distance11 + weight27 < distance27:
            distance27 = distance11 + weight27
            direction27 = direction11

        if distance25 + weight27 < distance27:
            distance27 = distance25 + weight27
            direction27 = direction25

        if distance9 + weight27 < distance27:
            distance27 = distance9 + weight27
            direction27 = direction9

        if distance22 + weight27 < distance27:
            distance27 = distance22 + weight27
            direction27 = direction22
        #}

        #if (canVisit31) {
        if distance13 + weight31 < distance31:
            distance31 = distance13 + weight31
            direction31 = direction13

        if distance30 + weight31 < distance31:
            distance31 = distance30 + weight31
            direction31 = direction30

        if distance23 + weight31 < distance31:
            distance31 = distance23 + weight31
            direction31 = direction23

        if distance12 + weight31 < distance31:
            distance31 = distance12 + weight31
            direction31 = direction12
        #}

        #if (canVisit32) {
        if distance14 + weight32 < distance32:
            distance32 = distance14 + weight32
            direction32 = direction14

        if distance30 + weight32 < distance32:
            distance32 = distance30 + weight32
            direction32 = direction30

        if distance12 + weight32 < distance32:
            distance32 = distance12 + weight32
            direction32 = direction12

        if distance24 + weight32 < distance32:
            distance32 = distance24 + weight32
            direction32 = direction24
        #}

        #if (canVisit36) {
        if distance35 + weight36 < distance36:
            distance36 = distance35 + weight36
            direction36 = direction35

        if distance16 + weight36 < distance36:
            distance36 = distance16 + weight36
            direction36 = direction16

        if distance21 + weight36 < distance36:
            distance36 = distance21 + weight36
            direction36 = direction21

        if distance15 + weight36 < distance36:
            distance36 = distance15 + weight36
            direction36 = direction15
        #}

        #if (canVisit37) {
        if distance35 + weight37 < distance37:
            distance37 = distance35 + weight37
            direction37 = direction35

        if distance17 + weight37 < distance37:
            distance37 = distance17 + weight37
            direction37 = direction17

        if distance15 + weight37 < distance37:
            distance37 = distance15 + weight37
            direction37 = direction15

        if distance23 + weight37 < distance37:
            distance37 = distance23 + weight37
            direction37 = direction23
        #}

        #if (canVisit41) {
        if distance40 + weight41 < distance41:
            distance41 = distance40 + weight41
            direction41 = direction40

        if distance19 + weight41 < distance41:
            distance41 = distance19 + weight41
            direction41 = direction19

        if distance22 + weight41 < distance41:
            distance41 = distance22 + weight41
            direction41 = direction22

        if distance18 + weight41 < distance41:
            distance41 = distance18 + weight41
            direction41 = direction18
        #}

        #if (canVisit42) {
        if distance40 + weight42 < distance42:
            distance42 = distance40 + weight42
            direction42 = direction40

        if distance20 + weight42 < distance42:
            distance42 = distance20 + weight42
            direction42 = direction20

        if distance18 + weight42 < distance42:
            distance42 = distance18 + weight42
            direction42 = direction18

        if distance24 + weight42 < distance42:
            distance42 = distance24 + weight42
            direction42 = direction24
        #}

        #if (canVisit28) {
        if distance21 + weight28 < distance28:
            distance28 = distance21 + weight28
            direction28 = direction21

        if distance26 + weight28 < distance28:
            distance28 = distance26 + weight28
            direction28 = direction26

        if distance10 + weight28 < distance28:
            distance28 = distance10 + weight28
            direction28 = direction10
        #}

        #if (canVisit29) {
        if distance22 + weight29 < distance29:
            distance29 = distance22 + weight29
            direction29 = direction22

        if distance27 + weight29 < distance29:
            distance29 = distance27 + weight29
            direction29 = direction27

        if distance11 + weight29 < distance29:
            distance29 = distance11 + weight29
            direction29 = direction11
        #}

        #if (canVisit33) {
        if distance23 + weight33 < distance33:
            distance33 = distance23 + weight33
            direction33 = direction23

        if distance31 + weight33 < distance33:
            distance33 = distance31 + weight33
            direction33 = direction31

        if distance13 + weight33 < distance33:
            distance33 = distance13 + weight33
            direction33 = direction13
        #}

        #if (canVisit34) {
        if distance24 + weight34 < distance34:
            distance34 = distance24 + weight34
            direction34 = direction24

        if distance32 + weight34 < distance34:
            distance34 = distance32 + weight34
            direction34 = direction32

        if distance14 + weight34 < distance34:
            distance34 = distance14 + weight34
            direction34 = direction14
        #}

        #if (canVisit38) {
        if distance36 + weight38 < distance38:
            distance38 = distance36 + weight38
            direction38 = direction36

        if distance21 + weight38 < distance38:
            distance38 = distance21 + weight38
            direction38 = direction21

        if distance16 + weight38 < distance38:
            distance38 = distance16 + weight38
            direction38 = direction16
        #}

        #if (canVisit39) {
        if distance37 + weight39 < distance39:
            distance39 = distance37 + weight39
            direction39 = direction37

        if distance23 + weight39 < distance39:
            distance39 = distance23 + weight39
            direction39 = direction23

        if distance17 + weight39 < distance39:
            distance39 = distance17 + weight39
            direction39 = direction17
        #}

        #if (canVisit43) {
        if distance41 + weight43 < distance43:
            distance43 = distance41 + weight43
            direction43 = direction41

        if distance22 + weight43 < distance43:
            distance43 = distance22 + weight43
            direction43 = direction22

        if distance19 + weight43 < distance43:
            distance43 = distance19 + weight43
            direction43 = direction19
        #}

        #if (canVisit44) {
        if distance42 + weight44 < distance44:
            distance44 = distance42 + weight44
            direction44 = direction42

        if distance24 + weight44 < distance44:
            distance44 = distance24 + weight44
            direction44 = direction24

        if distance20 + weight44 < distance44:
            distance44 = distance20 + weight44
            direction44 = direction20
        #}

        #if (canVisit44) {
        if distance34 + weight44 < distance44:
            distance44 = distance34 + weight44
            direction44 = direction34
        #}

        #if (canVisit43) {
        if distance29 + weight43 < distance43:
            distance43 = distance29 + weight43
            direction43 = direction29
        #}

        #if (canVisit39) {
        if distance33 + weight39 < distance39:
            distance39 = distance33 + weight39
            direction39 = direction33
        #}

        #if (canVisit38) {
        if distance28 + weight38 < distance38:
            distance38 = distance28 + weight38
            direction38 = direction28
        #}

        #if (canVisit34) {
        if distance44 + weight34 < distance34:
            distance34 = distance44 + weight34
            direction34 = direction44
        #}

        #if (canVisit33) {
        if distance39 + weight33 < distance33:
            distance33 = distance39 + weight33
            direction33 = direction39
        #}

        #if (canVisit29) {
        if distance43 + weight29 < distance29:
            distance29 = distance43 + weight29
            direction29 = direction43
        #}

        #if (canVisit28) {
        if distance38 + weight28 < distance28:
            distance28 = distance38 + weight28
            direction28 = direction38
        #}

        #if (canVisit42) {
        if distance44 + weight42 < distance42:
            distance42 = distance44 + weight42
            direction42 = direction44
        #}

        #if (canVisit41) {
        if distance43 + weight41 < distance41:
            distance41 = distance43 + weight41
            direction41 = direction43
        #}

        #if (canVisit37) {
        if distance39 + weight37 < distance37:
            distance37 = distance39 + weight37
            direction37 = direction39
        #}

        #if (canVisit36) {
        if distance38 + weight36 < distance36:
            distance36 = distance38 + weight36
            direction36 = direction38
        #}

        #if (canVisit32) {
        if distance34 + weight32 < distance32:
            distance32 = distance34 + weight32
            direction32 = direction34
        #}

        #if (canVisit31) {
        if distance33 + weight31 < distance31:
            distance31 = distance33 + weight31
            direction31 = direction33
        #}

        #if (canVisit27) {
        if distance29 + weight27 < distance27:
            distance27 = distance29 + weight27
            direction27 = direction29
        #}

        #if (canVisit26) {
        if distance28 + weight26 < distance26:
            distance26 = distance28 + weight26
            direction26 = direction28
        #}

        #if (canVisit40) {
        if distance41 + weight40 < distance40:
            distance40 = distance41 + weight40
            direction40 = direction41

        if distance42 + weight40 < distance40:
            distance40 = distance42 + weight40
            direction40 = direction42
        #}

        #if (canVisit35) {
        if distance36 + weight35 < distance35:
            distance35 = distance36 + weight35
            direction35 = direction36

        if distance37 + weight35 < distance35:
            distance35 = distance37 + weight35
            direction35 = direction37
        #}

        #if (canVisit30) {
        if distance31 + weight30 < distance30:
            distance30 = distance31 + weight30
            direction30 = direction31

        if distance32 + weight30 < distance30:
            distance30 = distance32 + weight30
            direction30 = direction32
        #}

        #if (canVisit25) {
        if distance26 + weight25 < distance25:
            distance25 = distance26 + weight25
            direction25 = direction26

        if distance27 + weight25 < distance25:
            distance25 = distance27 + weight25
            direction25 = direction27
        #}

        #if (canVisit24) {
        if distance34 + weight24 < distance24:
            distance24 = distance34 + weight24
            direction24 = direction34

        if distance44 + weight24 < distance24:
            distance24 = distance44 + weight24
            direction24 = direction44

        if distance42 + weight24 < distance24:
            distance24 = distance42 + weight24
            direction24 = direction42

        if distance32 + weight24 < distance24:
            distance24 = distance32 + weight24
            direction24 = direction32
        #}

        #if (canVisit23) {
        if distance33 + weight23 < distance23:
            distance23 = distance33 + weight23
            direction23 = direction33

        if distance39 + weight23 < distance23:
            distance23 = distance39 + weight23
            direction23 = direction39

        if distance37 + weight23 < distance23:
            distance23 = distance37 + weight23
            direction23 = direction37

        if distance31 + weight23 < distance23:
            distance23 = distance31 + weight23
            direction23 = direction31
        #}

        #if (canVisit22) {
        if distance29 + weight22 < distance22:
            distance22 = distance29 + weight22
            direction22 = direction29

        if distance43 + weight22 < distance22:
            distance22 = distance43 + weight22
            direction22 = direction43

        if distance27 + weight22 < distance22:
            distance22 = distance27 + weight22
            direction22 = direction27

        if distance41 + weight22 < distance22:
            distance22 = distance41 + weight22
            direction22 = direction41
        #}

        #if (canVisit21) {
        if distance28 + weight21 < distance21:
            distance21 = distance28 + weight21
            direction21 = direction28

        if distance38 + weight21 < distance21:
            distance21 = distance38 + weight21
            direction21 = direction38

        if distance26 + weight21 < distance21:
            distance21 = distance26 + weight21
            direction21 = direction26

        if distance36 + weight21 < distance21:
            distance21 = distance36 + weight21
            direction21 = direction36
        #}

        #if (canVisit20) {
        if distance24 + weight20 < distance20:
            distance20 = distance24 + weight20
            direction20 = direction24

        if distance42 + weight20 < distance20:
            distance20 = distance42 + weight20
            direction20 = direction42

        if distance40 + weight20 < distance20:
            distance20 = distance40 + weight20
            direction20 = direction40

        if distance14 + weight20 < distance20:
            distance20 = distance14 + weight20
            direction20 = direction14

        if distance44 + weight20 < distance20:
            distance20 = distance44 + weight20
            direction20 = direction44
        #}

        #if (canVisit19) {
        if distance22 + weight19 < distance19:
            distance19 = distance22 + weight19
            direction19 = direction22

        if distance41 + weight19 < distance19:
            distance19 = distance41 + weight19
            direction19 = direction41

        if distance11 + weight19 < distance19:
            distance19 = distance11 + weight19
            direction19 = direction11

        if distance43 + weight19 < distance19:
            distance19 = distance43 + weight19
            direction19 = direction43

        if distance40 + weight19 < distance19:
            distance19 = distance40 + weight19
            direction19 = direction40
        #}

        #if (canVisit17) {
        if distance23 + weight17 < distance17:
            distance17 = distance23 + weight17
            direction17 = direction23

        if distance37 + weight17 < distance17:
            distance17 = distance37 + weight17
            direction17 = direction37

        if distance35 + weight17 < distance17:
            distance17 = distance35 + weight17
            direction17 = direction35

        if distance39 + weight17 < distance17:
            distance17 = distance39 + weight17
            direction17 = direction39

        if distance13 + weight17 < distance17:
            distance17 = distance13 + weight17
            direction17 = direction13
        #}

        #if (canVisit16) {
        if distance21 + weight16 < distance16:
            distance16 = distance21 + weight16
            direction16 = direction21

        if distance36 + weight16 < distance16:
            distance16 = distance36 + weight16
            direction16 = direction36

        if distance38 + weight16 < distance16:
            distance16 = distance38 + weight16
            direction16 = direction38

        if distance10 + weight16 < distance16:
            distance16 = distance10 + weight16
            direction16 = direction10

        if distance35 + weight16 < distance16:
            distance16 = distance35 + weight16
            direction16 = direction35
        #}

        #if (canVisit14) {
        if distance32 + weight14 < distance14:
            distance14 = distance32 + weight14
            direction14 = direction32

        if distance24 + weight14 < distance14:
            distance14 = distance24 + weight14
            direction14 = direction24

        if distance20 + weight14 < distance14:
            distance14 = distance20 + weight14
            direction14 = direction20

        if distance30 + weight14 < distance14:
            distance14 = distance30 + weight14
            direction14 = direction30

        if distance34 + weight14 < distance14:
            distance14 = distance34 + weight14
            direction14 = direction34
        #}

        #if (canVisit13) {
        if distance31 + weight13 < distance13:
            distance13 = distance31 + weight13
            direction13 = direction31

        if distance23 + weight13 < distance13:
            distance13 = distance23 + weight13
            direction13 = direction23

        if distance17 + weight13 < distance13:
            distance13 = distance17 + weight13
            direction13 = direction17

        if distance33 + weight13 < distance13:
            distance13 = distance33 + weight13
            direction13 = direction33

        if distance30 + weight13 < distance13:
            distance13 = distance30 + weight13
            direction13 = direction30
        #}

        #if (canVisit11) {
        if distance27 + weight11 < distance11:
            distance11 = distance27 + weight11
            direction11 = direction27

        if distance22 + weight11 < distance11:
            distance11 = distance22 + weight11
            direction11 = direction22

        if distance25 + weight11 < distance11:
            distance11 = distance25 + weight11
            direction11 = direction25

        if distance29 + weight11 < distance11:
            distance11 = distance29 + weight11
            direction11 = direction29

        if distance19 + weight11 < distance11:
            distance11 = distance19 + weight11
            direction11 = direction19
        #}

        #if (canVisit10) {
        if distance26 + weight10 < distance10:
            distance10 = distance26 + weight10
            direction10 = direction26

        if distance21 + weight10 < distance10:
            distance10 = distance21 + weight10
            direction10 = direction21

        if distance28 + weight10 < distance10:
            distance10 = distance28 + weight10
            direction10 = direction28

        if distance25 + weight10 < distance10:
            distance10 = distance25 + weight10
            direction10 = direction25

        if distance16 + weight10 < distance10:
            distance10 = distance16 + weight10
            direction10 = direction16
        #}

        #if (canVisit18) {
        if distance19 + weight18 < distance18:
            distance18 = distance19 + weight18
            direction18 = direction19

        if distance20 + weight18 < distance18:
            distance18 = distance20 + weight18
            direction18 = direction20

        if distance40 + weight18 < distance18:
            distance18 = distance40 + weight18
            direction18 = direction40

        if distance41 + weight18 < distance18:
            distance18 = distance41 + weight18
            direction18 = direction41

        if distance42 + weight18 < distance18:
            distance18 = distance42 + weight18
            direction18 = direction42
        #}

        #if (canVisit15) {
        if distance16 + weight15 < distance15:
            distance15 = distance16 + weight15
            direction15 = direction16

        if distance17 + weight15 < distance15:
            distance15 = distance17 + weight15
            direction15 = direction17

        if distance35 + weight15 < distance15:
            distance15 = distance35 + weight15
            direction15 = direction35

        if distance36 + weight15 < distance15:
            distance15 = distance36 + weight15
            direction15 = direction36

        if distance37 + weight15 < distance15:
            distance15 = distance37 + weight15
            direction15 = direction37
        #}

        #if (canVisit12) {
        if distance30 + weight12 < distance12:
            distance12 = distance30 + weight12
            direction12 = direction30

        if distance13 + weight12 < distance12:
            distance12 = distance13 + weight12
            direction12 = direction13

        if distance14 + weight12 < distance12:
            distance12 = distance14 + weight12
            direction12 = direction14

        if distance31 + weight12 < distance12:
            distance12 = distance31 + weight12
            direction12 = direction31

        if distance32 + weight12 < distance12:
            distance12 = distance32 + weight12
            direction12 = direction32
        #}

        #if (canVisit9) {
        if distance25 + weight9 < distance9:
            distance9 = distance25 + weight9
            direction9 = direction25

        if distance10 + weight9 < distance9:
            distance9 = distance10 + weight9
            direction9 = direction10

        if distance11 + weight9 < distance9:
            distance9 = distance11 + weight9
            direction9 = direction11

        if distance26 + weight9 < distance9:
            distance9 = distance26 + weight9
            direction9 = direction26

        if distance27 + weight9 < distance9:
            distance9 = distance27 + weight9
            direction9 = direction27
        #}

        #if (canVisit8) {
        if distance14 + weight8 < distance8:
            distance8 = distance14 + weight8
            direction8 = direction14

        if distance20 + weight8 < distance8:
            distance8 = distance20 + weight8
            direction8 = direction20

        if distance18 + weight8 < distance8:
            distance8 = distance18 + weight8
            direction8 = direction18

        if distance12 + weight8 < distance8:
            distance8 = distance12 + weight8
            direction8 = direction12

        if distance24 + weight8 < distance8:
            distance8 = distance24 + weight8
            direction8 = direction24
        #}

        #if (canVisit7) {
        if distance13 + weight7 < distance7:
            distance7 = distance13 + weight7
            direction7 = direction13

        if distance17 + weight7 < distance7:
            distance7 = distance17 + weight7
            direction7 = direction17

        if distance15 + weight7 < distance7:
            distance7 = distance15 + weight7
            direction7 = direction15

        if distance23 + weight7 < distance7:
            distance7 = distance23 + weight7
            direction7 = direction23

        if distance12 + weight7 < distance7:
            distance7 = distance12 + weight7
            direction7 = direction12
        #}

        #if (canVisit6) {
        if distance11 + weight6 < distance6:
            distance6 = distance11 + weight6
            direction6 = direction11

        if distance19 + weight6 < distance6:
            distance6 = distance19 + weight6
            direction6 = direction19

        if distance9 + weight6 < distance6:
            distance6 = distance9 + weight6
            direction6 = direction9

        if distance22 + weight6 < distance6:
            distance6 = distance22 + weight6
            direction6 = direction22

        if distance18 + weight6 < distance6:
            distance6 = distance18 + weight6
            direction6 = direction18
        #}

        #if (canVisit5) {
        if distance10 + weight5 < distance5:
            distance5 = distance10 + weight5
            direction5 = direction10

        if distance16 + weight5 < distance5:
            distance5 = distance16 + weight5
            direction5 = direction16

        if distance21 + weight5 < distance5:
            distance5 = distance21 + weight5
            direction5 = direction21

        if distance9 + weight5 < distance5:
            distance5 = distance9 + weight5
            direction5 = direction9

        if distance15 + weight5 < distance5:
            distance5 = distance15 + weight5
            direction5 = direction15
        #}

        #if (canVisit4) {
        if distance6 + weight4 < distance4:
            distance4 = distance6 + weight4
            direction4 = direction6

        if distance8 + weight4 < distance4:
            distance4 = distance8 + weight4
            direction4 = direction8

        if distance18 + weight4 < distance4:
            distance4 = distance18 + weight4
            direction4 = direction18

        if distance1 + weight4 < distance4:
            distance4 = distance1 + weight4
            direction4 = direction1

        if distance19 + weight4 < distance4:
            distance4 = distance19 + weight4
            direction4 = direction19

        if distance2 + weight4 < distance4:
            distance4 = distance2 + weight4
            direction4 = direction2

        if distance20 + weight4 < distance4:
            distance4 = distance20 + weight4
            direction4 = direction20
        #}

        #if (canVisit3) {
        if distance5 + weight3 < distance3:
            distance3 = distance5 + weight3
            direction3 = direction5

        if distance7 + weight3 < distance3:
            distance3 = distance7 + weight3
            direction3 = direction7

        if distance15 + weight3 < distance3:
            distance3 = distance15 + weight3
            direction3 = direction15

        if distance16 + weight3 < distance3:
            distance3 = distance16 + weight3
            direction3 = direction16

        if distance1 + weight3 < distance3:
            distance3 = distance1 + weight3
            direction3 = direction1

        if distance17 + weight3 < distance3:
            distance3 = distance17 + weight3
            direction3 = direction17

        if distance2 + weight3 < distance3:
            distance3 = distance2 + weight3
            direction3 = direction2
        #}

        #if (canVisit2) {
        if distance12 + weight2 < distance2:
            distance2 = distance12 + weight2
            direction2 = direction12

        if distance7 + weight2 < distance2:
            distance2 = distance7 + weight2
            direction2 = direction7

        if distance8 + weight2 < distance2:
            distance2 = distance8 + weight2
            direction2 = direction8

        if distance3 + weight2 < distance2:
            distance2 = distance3 + weight2
            direction2 = direction3

        if distance4 + weight2 < distance2:
            distance2 = distance4 + weight2
            direction2 = direction4

        if distance13 + weight2 < distance2:
            distance2 = distance13 + weight2
            direction2 = direction13

        if distance14 + weight2 < distance2:
            distance2 = distance14 + weight2
            direction2 = direction14
        #}

        #if (canVisit1) {
        if distance9 + weight1 < distance1:
            distance1 = distance9 + weight1
            direction1 = direction9

        if distance5 + weight1 < distance1:
            distance1 = distance5 + weight1
            direction1 = direction5

        if distance6 + weight1 < distance1:
            distance1 = distance6 + weight1
            direction1 = direction6

        if distance10 + weight1 < distance1:
            distance1 = distance10 + weight1
            direction1 = direction10

        if distance11 + weight1 < distance1:
            distance1 = distance11 + weight1
            direction1 = direction11

        if distance3 + weight1 < distance1:
            distance1 = distance3 + weight1
            direction1 = direction3

        if distance4 + weight1 < distance1:
            distance1 = distance4 + weight1
            direction1 = direction4
        #}

        #if (canVisit5) {
        if distance3 + weight5 < distance5:
            distance5 = distance3 + weight5
            direction5 = direction3

        if distance1 + weight5 < distance5:
            distance5 = distance1 + weight5
            direction5 = direction1
        #}

        #if (canVisit6) {
        if distance4 + weight6 < distance6:
            distance6 = distance4 + weight6
            direction6 = direction4

        if distance1 + weight6 < distance6:
            distance6 = distance1 + weight6
            direction6 = direction1
        #}

        #if (canVisit7) {
        if distance3 + weight7 < distance7:
            distance7 = distance3 + weight7
            direction7 = direction3

        if distance2 + weight7 < distance7:
            distance7 = distance2 + weight7
            direction7 = direction2
        #}

        #if (canVisit8) {
        if distance4 + weight8 < distance8:
            distance8 = distance4 + weight8
            direction8 = direction4

        if distance2 + weight8 < distance8:
            distance8 = distance2 + weight8
            direction8 = direction2
        #}

        #if (canVisit9) {
        if distance1 + weight9 < distance9:
            distance9 = distance1 + weight9
            direction9 = direction1

        if distance5 + weight9 < distance9:
            distance9 = distance5 + weight9
            direction9 = direction5

        if distance6 + weight9 < distance9:
            distance9 = distance6 + weight9
            direction9 = direction6
        #}

        #if (canVisit12) {
        if distance2 + weight12 < distance12:
            distance12 = distance2 + weight12
            direction12 = direction2

        if distance7 + weight12 < distance12:
            distance12 = distance7 + weight12
            direction12 = direction7

        if distance8 + weight12 < distance12:
            distance12 = distance8 + weight12
            direction12 = direction8
        #}

        #if (canVisit15) {
        if distance3 + weight15 < distance15:
            distance15 = distance3 + weight15
            direction15 = direction3

        if distance5 + weight15 < distance15:
            distance15 = distance5 + weight15
            direction15 = direction5

        if distance7 + weight15 < distance15:
            distance15 = distance7 + weight15
            direction15 = direction7
        #}

        #if (canVisit18) {
        if distance4 + weight18 < distance18:
            distance18 = distance4 + weight18
            direction18 = direction4

        if distance6 + weight18 < distance18:
            distance18 = distance6 + weight18
            direction18 = direction6

        if distance8 + weight18 < distance18:
            distance18 = distance8 + weight18
            direction18 = direction8
        #}

        #if (canVisit10) {
        if distance5 + weight10 < distance10:
            distance10 = distance5 + weight10
            direction10 = direction5

        if distance9 + weight10 < distance10:
            distance10 = distance9 + weight10
            direction10 = direction9

        if distance1 + weight10 < distance10:
            distance10 = distance1 + weight10
            direction10 = direction1
        #}

        #if (canVisit11) {
        if distance6 + weight11 < distance11:
            distance11 = distance6 + weight11
            direction11 = direction6

        if distance9 + weight11 < distance11:
            distance11 = distance9 + weight11
            direction11 = direction9

        if distance1 + weight11 < distance11:
            distance11 = distance1 + weight11
            direction11 = direction1
        #}

        #if (canVisit13) {
        if distance7 + weight13 < distance13:
            distance13 = distance7 + weight13
            direction13 = direction7

        if distance12 + weight13 < distance13:
            distance13 = distance12 + weight13
            direction13 = direction12

        if distance2 + weight13 < distance13:
            distance13 = distance2 + weight13
            direction13 = direction2
        #}

        #if (canVisit14) {
        if distance8 + weight14 < distance14:
            distance14 = distance8 + weight14
            direction14 = direction8

        if distance12 + weight14 < distance14:
            distance14 = distance12 + weight14
            direction14 = direction12

        if distance2 + weight14 < distance14:
            distance14 = distance2 + weight14
            direction14 = direction2
        #}

        #if (canVisit16) {
        if distance15 + weight16 < distance16:
            distance16 = distance15 + weight16
            direction16 = direction15

        if distance5 + weight16 < distance16:
            distance16 = distance5 + weight16
            direction16 = direction5

        if distance3 + weight16 < distance16:
            distance16 = distance3 + weight16
            direction16 = direction3
        #}

        #if (canVisit17) {
        if distance15 + weight17 < distance17:
            distance17 = distance15 + weight17
            direction17 = direction15

        if distance7 + weight17 < distance17:
            distance17 = distance7 + weight17
            direction17 = direction7

        if distance3 + weight17 < distance17:
            distance17 = distance3 + weight17
            direction17 = direction3
        #}

        #if (canVisit19) {
        if distance18 + weight19 < distance19:
            distance19 = distance18 + weight19
            direction19 = direction18

        if distance6 + weight19 < distance19:
            distance19 = distance6 + weight19
            direction19 = direction6

        if distance4 + weight19 < distance19:
            distance19 = distance4 + weight19
            direction19 = direction4
        #}

        #if (canVisit20) {
        if distance18 + weight20 < distance20:
            distance20 = distance18 + weight20
            direction20 = direction18

        if distance8 + weight20 < distance20:
            distance20 = distance8 + weight20
            direction20 = direction8

        if distance4 + weight20 < distance20:
            distance20 = distance4 + weight20
            direction20 = direction4
        #}

        #if (canVisit21) {
        if distance16 + weight21 < distance21:
            distance21 = distance16 + weight21
            direction21 = direction16

        if distance10 + weight21 < distance21:
            distance21 = distance10 + weight21
            direction21 = direction10

        if distance5 + weight21 < distance21:
            distance21 = distance5 + weight21
            direction21 = direction5
        #}

        #if (canVisit22) {
        if distance19 + weight22 < distance22:
            distance22 = distance19 + weight22
            direction22 = direction19

        if distance11 + weight22 < distance22:
            distance22 = distance11 + weight22
            direction22 = direction11

        if distance6 + weight22 < distance22:
            distance22 = distance6 + weight22
            direction22 = direction6
        #}

        #if (canVisit23) {
        if distance17 + weight23 < distance23:
            distance23 = distance17 + weight23
            direction23 = direction17

        if distance13 + weight23 < distance23:
            distance23 = distance13 + weight23
            direction23 = direction13

        if distance7 + weight23 < distance23:
            distance23 = distance7 + weight23
            direction23 = direction7
        #}

        #if (canVisit24) {
        if distance20 + weight24 < distance24:
            distance24 = distance20 + weight24
            direction24 = direction20

        if distance14 + weight24 < distance24:
            distance24 = distance14 + weight24
            direction24 = direction14

        if distance8 + weight24 < distance24:
            distance24 = distance8 + weight24
            direction24 = direction8
        #}

        #if (canVisit25) {
        if distance9 + weight25 < distance25:
            distance25 = distance9 + weight25
            direction25 = direction9

        if distance10 + weight25 < distance25:
            distance25 = distance10 + weight25
            direction25 = direction10

        if distance11 + weight25 < distance25:
            distance25 = distance11 + weight25
            direction25 = direction11
        #}

        #if (canVisit30) {
        if distance12 + weight30 < distance30:
            distance30 = distance12 + weight30
            direction30 = direction12

        if distance13 + weight30 < distance30:
            distance30 = distance13 + weight30
            direction30 = direction13

        if distance14 + weight30 < distance30:
            distance30 = distance14 + weight30
            direction30 = direction14
        #}

        #if (canVisit35) {
        if distance15 + weight35 < distance35:
            distance35 = distance15 + weight35
            direction35 = direction15

        if distance16 + weight35 < distance35:
            distance35 = distance16 + weight35
            direction35 = direction16

        if distance17 + weight35 < distance35:
            distance35 = distance17 + weight35
            direction35 = direction17
        #}

        #if (canVisit40) {
        if distance18 + weight40 < distance40:
            distance40 = distance18 + weight40
            direction40 = direction18

        if distance19 + weight40 < distance40:
            distance40 = distance19 + weight40
            direction40 = direction19

        if distance20 + weight40 < distance40:
            distance40 = distance20 + weight40
            direction40 = direction20
        #}

        #if (canVisit26) {
        if distance10 + weight26 < distance26:
            distance26 = distance10 + weight26
            direction26 = direction10

        if distance25 + weight26 < distance26:
            distance26 = distance25 + weight26
            direction26 = direction25

        if distance21 + weight26 < distance26:
            distance26 = distance21 + weight26
            direction26 = direction21

        if distance9 + weight26 < distance26:
            distance26 = distance9 + weight26
            direction26 = direction9
        #}

        #if (canVisit27) {
        if distance11 + weight27 < distance27:
            distance27 = distance11 + weight27
            direction27 = direction11

        if distance25 + weight27 < distance27:
            distance27 = distance25 + weight27
            direction27 = direction25

        if distance9 + weight27 < distance27:
            distance27 = distance9 + weight27
            direction27 = direction9

        if distance22 + weight27 < distance27:
            distance27 = distance22 + weight27
            direction27 = direction22
        #}

        #if (canVisit31) {
        if distance13 + weight31 < distance31:
            distance31 = distance13 + weight31
            direction31 = direction13

        if distance30 + weight31 < distance31:
            distance31 = distance30 + weight31
            direction31 = direction30

        if distance23 + weight31 < distance31:
            distance31 = distance23 + weight31
            direction31 = direction23

        if distance12 + weight31 < distance31:
            distance31 = distance12 + weight31
            direction31 = direction12
        #}

        #if (canVisit32) {
        if distance14 + weight32 < distance32:
            distance32 = distance14 + weight32
            direction32 = direction14

        if distance30 + weight32 < distance32:
            distance32 = distance30 + weight32
            direction32 = direction30

        if distance12 + weight32 < distance32:
            distance32 = distance12 + weight32
            direction32 = direction12

        if distance24 + weight32 < distance32:
            distance32 = distance24 + weight32
            direction32 = direction24
        #}

        #if (canVisit36) {
        if distance35 + weight36 < distance36:
            distance36 = distance35 + weight36
            direction36 = direction35

        if distance16 + weight36 < distance36:
            distance36 = distance16 + weight36
            direction36 = direction16

        if distance21 + weight36 < distance36:
            distance36 = distance21 + weight36
            direction36 = direction21

        if distance15 + weight36 < distance36:
            distance36 = distance15 + weight36
            direction36 = direction15
        #}

        #if (canVisit37) {
        if distance35 + weight37 < distance37:
            distance37 = distance35 + weight37
            direction37 = direction35

        if distance17 + weight37 < distance37:
            distance37 = distance17 + weight37
            direction37 = direction17

        if distance15 + weight37 < distance37:
            distance37 = distance15 + weight37
            direction37 = direction15

        if distance23 + weight37 < distance37:
            distance37 = distance23 + weight37
            direction37 = direction23
        #}

        #if (canVisit41) {
        if distance40 + weight41 < distance41:
            distance41 = distance40 + weight41
            direction41 = direction40

        if distance19 + weight41 < distance41:
            distance41 = distance19 + weight41
            direction41 = direction19

        if distance22 + weight41 < distance41:
            distance41 = distance22 + weight41
            direction41 = direction22

        if distance18 + weight41 < distance41:
            distance41 = distance18 + weight41
            direction41 = direction18
        #}

        #if (canVisit42) {
        if distance40 + weight42 < distance42:
            distance42 = distance40 + weight42
            direction42 = direction40

        if distance20 + weight42 < distance42:
            distance42 = distance20 + weight42
            direction42 = direction20

        if distance18 + weight42 < distance42:
            distance42 = distance18 + weight42
            direction42 = direction18

        if distance24 + weight42 < distance42:
            distance42 = distance24 + weight42
            direction42 = direction24
        #}

        #if (canVisit28) {
        if distance21 + weight28 < distance28:
            distance28 = distance21 + weight28
            direction28 = direction21

        if distance26 + weight28 < distance28:
            distance28 = distance26 + weight28
            direction28 = direction26

        if distance10 + weight28 < distance28:
            distance28 = distance10 + weight28
            direction28 = direction10
        #}

        #if (canVisit29) {
        if distance22 + weight29 < distance29:
            distance29 = distance22 + weight29
            direction29 = direction22

        if distance27 + weight29 < distance29:
            distance29 = distance27 + weight29
            direction29 = direction27

        if distance11 + weight29 < distance29:
            distance29 = distance11 + weight29
            direction29 = direction11
        #}

        #if (canVisit33) {
        if distance23 + weight33 < distance33:
            distance33 = distance23 + weight33
            direction33 = direction23

        if distance31 + weight33 < distance33:
            distance33 = distance31 + weight33
            direction33 = direction31

        if distance13 + weight33 < distance33:
            distance33 = distance13 + weight33
            direction33 = direction13
        #}

        #if (canVisit34) {
        if distance24 + weight34 < distance34:
            distance34 = distance24 + weight34
            direction34 = direction24

        if distance32 + weight34 < distance34:
            distance34 = distance32 + weight34
            direction34 = direction32

        if distance14 + weight34 < distance34:
            distance34 = distance14 + weight34
            direction34 = direction14
        #}

        #if (canVisit38) {
        if distance36 + weight38 < distance38:
            distance38 = distance36 + weight38
            direction38 = direction36

        if distance21 + weight38 < distance38:
            distance38 = distance21 + weight38
            direction38 = direction21

        if distance16 + weight38 < distance38:
            distance38 = distance16 + weight38
            direction38 = direction16
        #}

        #if (canVisit39) {
        if distance37 + weight39 < distance39:
            distance39 = distance37 + weight39
            direction39 = direction37

        if distance23 + weight39 < distance39:
            distance39 = distance23 + weight39
            direction39 = direction23

        if distance17 + weight39 < distance39:
            distance39 = distance17 + weight39
            direction39 = direction17
        #}

        #if (canVisit43) {
        if distance41 + weight43 < distance43:
            distance43 = distance41 + weight43
            direction43 = direction41

        if distance22 + weight43 < distance43:
            distance43 = distance22 + weight43
            direction43 = direction22

        if distance19 + weight43 < distance43:
            distance43 = distance19 + weight43
            direction43 = direction19
        #}

        #if (canVisit44) {
        if distance42 + weight44 < distance44:
            distance44 = distance42 + weight44
            direction44 = direction42

        if distance24 + weight44 < distance44:
            distance44 = distance24 + weight44
            direction44 = direction24

        if distance20 + weight44 < distance44:
            distance44 = distance20 + weight44
            direction44 = direction20
        #}

        bestDirection = None  # Java: /*, secondDirection = null*/ stayed commented
        bestScore = 0  # Java: /*secondScore = 0,*/ score declared but uninitialised
        currentDistance = Globals.rc.getLocation().distanceSquaredTo(target)

        score = (currentDistance - location21.distanceSquaredTo(target)) / distance21
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction21;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction21;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction21

        score = (currentDistance - location22.distanceSquaredTo(target)) / distance22
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction22;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction22;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction22

        score = (currentDistance - location23.distanceSquaredTo(target)) / distance23
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction23;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction23;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction23

        score = (currentDistance - location24.distanceSquaredTo(target)) / distance24
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction24;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction24;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction24

        score = (currentDistance - location25.distanceSquaredTo(target)) / distance25
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction25;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction25;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction25

        score = (currentDistance - location26.distanceSquaredTo(target)) / distance26
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction26;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction26;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction26

        score = (currentDistance - location27.distanceSquaredTo(target)) / distance27
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction27;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction27;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction27

        score = (currentDistance - location28.distanceSquaredTo(target)) / distance28
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction28;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction28;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction28

        score = (currentDistance - location29.distanceSquaredTo(target)) / distance29
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction29;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction29;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction29

        score = (currentDistance - location30.distanceSquaredTo(target)) / distance30
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction30;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction30;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction30

        score = (currentDistance - location31.distanceSquaredTo(target)) / distance31
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction31;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction31;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction31

        score = (currentDistance - location32.distanceSquaredTo(target)) / distance32
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction32;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction32;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction32

        score = (currentDistance - location33.distanceSquaredTo(target)) / distance33
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction33;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction33;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction33

        score = (currentDistance - location34.distanceSquaredTo(target)) / distance34
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction34;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction34;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction34

        score = (currentDistance - location35.distanceSquaredTo(target)) / distance35
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction35;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction35;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction35

        score = (currentDistance - location36.distanceSquaredTo(target)) / distance36
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction36;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction36;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction36

        score = (currentDistance - location37.distanceSquaredTo(target)) / distance37
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction37;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction37;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction37

        score = (currentDistance - location38.distanceSquaredTo(target)) / distance38
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction38;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction38;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction38

        score = (currentDistance - location39.distanceSquaredTo(target)) / distance39
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction39;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction39;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction39

        score = (currentDistance - location40.distanceSquaredTo(target)) / distance40
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction40;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction40;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction40

        score = (currentDistance - location41.distanceSquaredTo(target)) / distance41
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction41;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction41;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction41

        score = (currentDistance - location42.distanceSquaredTo(target)) / distance42
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction42;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction42;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction42

        score = (currentDistance - location43.distanceSquaredTo(target)) / distance43
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction43;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction43;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction43

        score = (currentDistance - location44.distanceSquaredTo(target)) / distance44
        # /*
        # if (score > secondScore) {
        #     if (score > bestScore) {
        #         secondDirection = bestDirection;
        #         secondScore = bestScore;
        #         bestDirection = direction44;
        #         bestScore = score;
        #     } else {
        #         secondDirection = direction44;
        #         secondScore = score;
        #     }
        # }
        # */
        if score > bestScore:
            bestScore = score
            bestDirection = direction44

        #return secondDirection == null ? bestDirection : (rng.nextDouble() < secondBestMoveChance ? secondDirection : bestDirection);
        return bestDirection
